#include "database.h"

char *weapon_db[] = {
"Nothing",
"Dagger",
"BallockKnife",
"Bronze Sword",
"Broad Sword",
"Silver Knife",
"Scramasax",
"Moon Sword",
"Claymore",
"Flare Sword",
"FeatherSword",
"Royal Dagger",
"Baselard",
"Deadly Blade",
"Heavy Dagger",
"Ascension",
"Heat Shotel",
"Barbarossa",
"PiercingEdge",
"Demonsbane",
"DamascusSwd",
"SeekingSword",
"Dragon Blade",
"Holy Avenger",
"Royal Sword",
"GooKingSword",
"AshurasSword",
"HiddenDagger",
"Bent Sword",
"PointedStick",
"Oaken Staff",
"Mace",
"Magician Rod",
"QuarterStaff",
"WindCutter",
"Ruby Scepter",
"LacquerStaff",
"Beryl Rod",
"Thunder Rod",
"BlessedStaff",
"Ouroboros",
"Spear",
"Long Spear",
"Halberd",
"Rood Spear",
"Flame Spear",
"Flying Spear",
"PiercingPike",
"Gigantess",
"Gale Javelin",
"Ice Halberd",
"Aries Spear",
"Gunginir",
"Dragon Spear",
"Rufad'sSpear",
"Claws",
"Rippers",
"Spiked Claws",
"Flame Talons",
"Tiger Claws",
"Raptor Claws",
"Rockbreaker",
"Brass Claws",
"Death Claws",
"Dragonfang",
"ThievesKnife",
"Katzbalger",
"Slicer",
"Lifestealer",
"Melted Blade",
"Ammo",
"Flame Chrysm",
"Ice Chrysm",
"ShotgunShell",
"Sleep Shells",
"HE Shells",
"Flash Shells",
"Homing Bomb",
"AP Shells",
"Gas Shells",
"Atomic Bomb",
"Ghostbuster",
"Beast Spear"
}; 
